project:
  type: website

website:
  page-navigation: true
  title: "STA 199"
  description: "Homepage for STA 199 - Introduction to Data Science at Duke University, Summer 2025."
  site-url: "https://sta199-su25.github.io/"

  repo-url: https://github.com/sta199-su25/sta199-su25.github.io
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@minebocek"
    image: "img/twitter-card.png"

  draft-mode: unlinked

  sidebar:
    background: "#f0bde9"
    logo: "img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta199-su25
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio containers"
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
          - href: coding-principles-oh.qmd
            text: Coding principles
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      - project/description.qmd
      - lab.qmd
      - ae.qmd
      - exam-review.qmd
            
  page-footer:
    right: 'This page is built with [{{< fa heart >}}]{style="color: #FFBE98;"} and [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025, Mine Çetinkaya-Rundel, Marie Neubrander"
    background: "#121940"

format: 
  html:
    mainfont: Roboto
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto

editor: visual
