---
title: "More Data Transformation"
subtitle: "Lecture 5"
date: "2025-05-19"
format: 
  revealjs:
    output-file: 04-data-transform-slides.html
auto-stretch: false
---

## Announcements/Reminders {.smaller}

-   Lab is due TONIGHT at 11:59PM

-   Come to office hours and/or post on Ed for help!

-   Office hours are tonight from **5:30-7:30PM** in **Old Chem 203**.

-   AEs need to be pushed by the **END OF CLASS (10:45AM)!!**

-   Make sure you are in the right repository.

## Lab: Narrative

## Outline {.smaller}

-   ***Last Time:*** Started learning about data transformation!

-   ***Today:***

    -   Review from last time + finish AE04

    -   More about the pipe

    -   Transformation + plotting

```{r}
#| label: slice
#| code-line-numbers: "|1|2"
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
bechdel <- read_csv("data/bechdel.csv")
```

## Quick Review: Row operations

-   `slice()`: chooses rows based on location
-   `filter()`:chooses rows based on column values
-   `arrange()`: changes the order of the rows
-   `sample_n()`: take a random subset of the rows

## Quick Review: Column Operations

-   `select()`: changes whether or not a column is included.
-   `rename()`: changes the name of columns.
-   `mutate()`: changes the values of columns and creates new columns.

## Quick Review: Groups of rows

-   `summarize()`: collapses a group into a single row.
-   `count()`: count unique values of one or more variables.
-   `group_by()`: perform calculations separately for each value of a variable



# AE-04

