<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-3e476e15ae565c222d94875412ae43a1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">
<meta name="dcterms.date" content="2025-06-19">
<title>STA 199 – More logistic regression</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #767676;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #767676;  padding-left: 4px; }
    div.sourceCode
      { color: #545454; background-color: #fefefe; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #545454; } /* Normal */
    code span.al { color: #7928a1; } /* Alert */
    code span.an { color: #696969; } /* Annotation */
    code span.at { color: #a55a00; } /* Attribute */
    code span.bn { color: #7928a1; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #d91e18; } /* ControlFlow */
    code span.ch { color: #008000; } /* Char */
    code span.cn { color: #d91e18; } /* Constant */
    code span.co { color: #696969; } /* Comment */
    code span.cv { color: #696969; font-style: italic; } /* CommentVar */
    code span.do { color: #696969; font-style: italic; } /* Documentation */
    code span.dt { color: #7928a1; } /* DataType */
    code span.dv { color: #7928a1; } /* DecVal */
    code span.er { color: #7928a1; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #a55a00; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #696969; } /* Information */
    code span.kw { color: #d91e18; } /* Keyword */
    code span.op { color: #00769e; } /* Operator */
    code span.ot { color: #d91e18; } /* Other */
    code span.pp { color: #7928a1; } /* Preprocessor */
    code span.sc { color: #00769e; } /* SpecialChar */
    code span.ss { color: #008000; } /* SpecialString */
    code span.st { color: #008000; } /* String */
    code span.va { color: #a55a00; } /* Variable */
    code span.vs { color: #008000; } /* VerbatimString */
    code span.wa { color: #696969; font-style: italic; } /* Warning */
  </style>
<link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8bc36ced1226147013789ff298d85564.css">
<link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="More logistic regression – STA 199">
<meta property="og:description" content="Lecture 19">
<meta property="og:site_name" content="STA 199">
<meta name="twitter:title" content="More logistic regression – STA 199">
<meta name="twitter:description" content="Lecture 19">
<meta name="twitter:image" content="https://sta199-su25.github.io/slides/img/twitter-card.png">
<meta name="twitter:creator" content="@minebocek">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">More logistic regression</h1>
  <p class="subtitle">Lecture 19</p>

<div class="quarto-title-authors">
</div>

  <p class="date">June 19, 2025</p>
</section><section id="while-you-wait" class="slide level2 smaller"><h2>While you wait…</h2>
<div class="appex">
<ul>
<li><p>Go to your <code>ae</code> project in RStudio.</p></li>
<li><p>Make sure all of your changes up to this point are committed and pushed, i.e., there’s nothing left in your Git pane.</p></li>
<li><p>Click Pull to get today’s application exercise file: <em>ae-14-spam-filter.qmd</em>.</p></li>
<li><p>Wait till the you’re prompted to work on the application exercise during class before editing the file.</p></li>
</ul>
</div>
</section><section id="announcements" class="slide level2"><h2>Announcements</h2>
<ul>
<li><p>Office hours tomorrow will be about 20 mins short (1:00 - 2:40). I will be there a little before 1:00 if you want to come early!</p></li>
<li><p>Make appointment to see in-class exams/talk through problems you’re stuck on. Remember, final exam is cumulative!!</p></li>
</ul></section><section id="project-reminders" class="slide level2"><h2>Project Reminders</h2>
<ul>
<li><p>Milestone 3 due Friday night!!</p></li>
<li><p>Once your project website renders, <strong>you still need to push</strong> for the changes to show up!!!</p></li>
</ul></section><section id="logistic-regression-recap" class="slide level2 smaller"><h2>Logistic Regression: Recap</h2>
<p><em>Goal</em>: modelling/predicting <strong><em>binary</em></strong> outcome <span class="math inline">\(y\)</span></p>
<ul>
<li>Idea: Model the probability <span class="math inline">\(p\)</span> that <span class="math inline">\(y = 1\)</span>
</li>
</ul>
<div class="fragment">
<ul>
<li>S-curve for the probability of success <span class="math inline">\(p=P(y=1)\)</span>:</li>
</ul>
<p><span class="math display">\[
    \hat{p} = \frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}.
   \]</span></p>
</div>
<div class="fragment">
<ul>
<li>Linear model for the log-odds:</li>
</ul>
<p><span class="math display">\[
    \log\left(\frac{\hat{p}}{1-\hat{p}}\right) = b_0+b_1x.
  \]</span></p>
</div>
</section><section id="r-syntax-is-mostly-unchanged" class="slide level2 smaller"><h2>R syntax is mostly unchanged</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>simple_logistic_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> exclaim_mess, <span class="at">data =</span> email)</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a><span class="fu">tidy</span>(simple_logistic_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.27      0.0553     -41.1     0    
2 exclaim_mess  0.000272  0.000949     0.287   0.774</code></pre>
</div>
</div>
<div class="fragment">
<p>Fitted equation for the log-odds:</p>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
</div>
<div class="fragment">
<p>Interpretations are strange and delicate.</p>
</div>
</section><section id="questions-review-anything" class="slide level2 smaller"><h2>Questions??? Review??? Anything?!</h2>
</section><section id="lets-practice" class="slide level2"><h2>Let’s Practice</h2>
<p>AE-14: Watch now, fill in later (optional!)</p>
</section><section id="goal" class="slide level2 smaller"><h2>Goal</h2>
<ul>
<li>We will build a spam filter from email data</li>
<li>The data come from incoming emails in David Diez’s (one of the authors of OpenIntro textbooks) Gmail account for the first three months of 2012</li>
<li>User number of exclamation marks in an email address (<code>exclaim_mess</code>) to predict whether or not the email is spam (<code>spam</code>: 1 if spam; 0 if not)</li>
</ul></section><section id="data" class="slide level2 smaller"><h2>Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">glimpse</span>(email)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,921
Columns: 21
$ spam         &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ to_multiple  &lt;fct&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ from         &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ cc           &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1,…
$ sent_email   &lt;fct&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,…
$ time         &lt;dttm&gt; 2012-01-01 01:16:41, 2012-01-01 02:03:59, 2012…
$ image        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ attach       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ dollar       &lt;dbl&gt; 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,…
$ winner       &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no,…
$ inherit      &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ viagra       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ password     &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ num_char     &lt;dbl&gt; 11.370, 10.504, 7.773, 13.256, 1.231, 1.091, 4.…
$ line_breaks  &lt;int&gt; 202, 202, 192, 255, 29, 25, 193, 237, 69, 68, 2…
$ format       &lt;fct&gt; 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,…
$ re_subj      &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,…
$ exclaim_subj &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ urgent_subj  &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ exclaim_mess &lt;dbl&gt; 0, 1, 6, 48, 1, 1, 1, 18, 1, 0, 2, 1, 0, 10, 4,…
$ number       &lt;fct&gt; big, small, small, small, none, none, big, smal…</code></pre>
</div>
</div>
</section><section id="eda-ex.-1" class="slide level2 smaller"><h2>EDA (Ex. 1)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-5-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="eda-ex.-1-1" class="slide level2 smaller"><h2>EDA (Ex. 1)</h2>
<p>Mean exclamation points by spam/not spam:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  spam  mean_ep
  &lt;fct&gt;   &lt;dbl&gt;
1 0        6.51
2 1        7.32</code></pre>
</div>
</div>
</section><section id="linear-model-ex.-2" class="slide level2 smaller"><h2>Linear Model (Ex. 2)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-7-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This makes no sense at all.</p>
</section><section id="fit-logistic-regression-ex.-3" class="slide level2 smaller"><h2>Fit Logistic Regression (Ex. 3)</h2>
<p>This is what we have seen already!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>spam_exl_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> exclaim_mess, <span class="at">data =</span> email)</span>
<span id="cb6-3"><a></a></span>
<span id="cb6-4"><a></a><span class="fu">tidy</span>(spam_exl_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.27      0.0553     -41.1     0    
2 exclaim_mess  0.000272  0.000949     0.287   0.774</code></pre>
</div>
</div>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
</section><section id="goal-predict-ex.-4a" class="slide level2 smaller"><h2>Goal: Predict!! (Ex. 4a)</h2>
<p><em>What is the probability the email is spam if it contains 10 exclamation points??</em> Use <code>predict</code>!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>new_email <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb8-2"><a></a>  <span class="at">exclaim_mess =</span> <span class="dv">10</span></span>
<span id="cb8-3"><a></a>  )</span>
<span id="cb8-4"><a></a></span>
<span id="cb8-5"><a></a>new_email</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  exclaim_mess
         &lt;dbl&gt;
1           10</code></pre>
</div>
</div>
</section><section id="goal-predict-ex.-4a-1" class="slide level2 smaller"><h2>Goal: Predict!! (Ex. 4a)</h2>
<p><em>What is the probability the email is spam if it contains 10 exclamation points??</em> Use <code>predict</code>!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>new_email <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb10-2"><a></a>  <span class="at">exclaim_mess =</span> <span class="dv">10</span></span>
<span id="cb10-3"><a></a>  )</span>
<span id="cb10-4"><a></a></span>
<span id="cb10-5"><a></a><span class="fu">predict</span>(spam_exl_fit, <span class="at">new_data =</span> new_email, <span class="at">type =</span> <span class="st">"prob"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  .pred_0 .pred_1
    &lt;dbl&gt;   &lt;dbl&gt;
1   0.906  0.0937</code></pre>
</div>
</div>
</section><section id="goal-predict-ex.-4b" class="slide level2 smaller"><h2>Goal: Predict!! (Ex. 4b)</h2>
<p><em>A probability is nice, but we want an actual decision. Classify the email!!!</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">predict</span>(spam_exl_fit, <span class="at">new_data =</span> new_email, <span class="at">type =</span> <span class="st">"class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  .pred_class
  &lt;fct&gt;      
1 0          </code></pre>
</div>
</div>
<div class="fragment">
<p>The default behavior is to threshold the probabilities by 0.5.</p>
</div>
</section><section id="lets-use-more-data-ex.-5a" class="slide level2 smaller"><h2>Let’s use more data (Ex. 5a)</h2>
<p>Why limit ourselves to using exclamation points???</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>spam_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> time <span class="sc">+</span> exclaim_mess <span class="sc">+</span> line_breaks, <span class="at">data =</span> email)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="lets-use-even-more-data-ex.-5b" class="slide level2 smaller"><h2>Let’s use even more data (Ex. 5b)</h2>
<p>What about all the predictors???</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>spam_all_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> ., <span class="at">data =</span> email)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
</div>
<p>The <code>.</code> means <em>all other variables</em> .</p>
</section><section id="is-our-model-good-ex.-5c" class="slide level2 smaller"><h2>Is our model good??? (Ex. 5c)</h2>
<ul>
<li>Goal is to evaluate how good our model is.</li>
<li>If you’re coding along: pause!! We’re going to review concepts first!!</li>
</ul></section><section id="reminder-classification-error" class="slide level2 smaller"><h2>Reminder: Classification Error</h2>
<p>There are two kinds of mistakes:</p>
<p><img data-src="images/18/confusion-matrix.png"></p>
<p>We want to avoid both, but there’s a trade-off.</p>
</section><section id="terms-false-negative-and-positive-rates" class="slide level2 smaller"><h2>Terms: False negative and positive rates</h2>
<ul>
<li><p><strong>False negative rate</strong> is the <em>proportion</em> of actual positives that were classified as negatives.</p></li>
<li><p><strong>False positive rate</strong> is the <em>proportion</em> of actual negatives that were classified as positives.</p></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want these to be low!</p>
</div>
</div>
</div>
</div>
</section><section id="terms-false-negative-and-positive-rates-1" class="slide level2 smaller"><h2>Terms: False negative and positive rates</h2>
<ul>
<li><p><strong>False negative rate</strong> = <span class="math inline">\(\frac{FN}{FN + TP}\)</span></p></li>
<li><p><strong>False positive rate</strong> = <span class="math inline">\(\frac{FP}{FP + TN}\)</span></p></li>
</ul>
<p><img data-src="images/18/confusion-matrix.png"></p>
</section><section id="term-sensitivity" class="slide level2 smaller"><h2>Term: Sensitivity</h2>
<p><strong>Sensitivity</strong> is the <em>proportion</em> of actual positives that were correctly classified as positive.</p>
<ul>
<li><p>Also known as <strong>true positive rate</strong> and <strong>recall</strong></p></li>
<li><p>Specificity = <span class="math inline">\(\frac{FN}{FN + TP}\)</span></p></li>
<li><p>Sensitivity = 1 − False negative rate</p></li>
<li><p>Useful when false negatives are more “expensive” than false positives</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want this to be high!</p>
</div>
</div>
</div>
</section><section id="term-specificity" class="slide level2 smaller"><h2>Term: Specificity</h2>
<p><strong>Specificity</strong> is the <em>proportion</em> of actual negatives that were correctly classified as negative</p>
<ul>
<li><p>Also known as <strong>true negative rate</strong></p></li>
<li><p>Specificity = <span class="math inline">\(\frac{TN}{FP + TN}\)</span></p></li>
<li><p>Specificity = 1 − False positive rate</p></li>
<li><p>Useful when false positives are more “expensive” than false negatives</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want this to be high!</p>
</div>
</div>
</div>
</section><section id="the-augment-function" class="slide level2 smaller"><h2>The augment function</h2>
<p>The <code>augment</code> function takes a data frame and “augments” it by adding three new columns on the left that describe the model predictions for each row:</p>
<div>
<ul>
<li class="fragment">
<code>.pred_class</code>: model prediction (<span class="math inline">\(\hat{y}\)</span>) based on a 50% threshold;</li>
<li class="fragment">
<code>.pred_0</code>: model estimate of <span class="math inline">\(P(y=0)\)</span>;</li>
<li class="fragment">
<code>.pred_1</code>: model estimate of <span class="math inline">\(P(y=1) = 1 - P(y = 0)\)</span>.</li>
</ul>
</div>
</section><section id="the-augment-function-1" class="slide level2 smaller"><h2>The augment function</h2>
<p>The <code>augment</code> function takes a data frame and “augments” it by adding three new columns on the left that describe the model predictions for each row:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>spam_aug_all <span class="ot">&lt;-</span> <span class="fu">augment</span>(spam_all_fit, email)</span>
<span id="cb17-2"><a></a>spam_aug_all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,921 × 24
   .pred_class .pred_0  .pred_1 spam  to_multiple from     cc
   &lt;fct&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;       &lt;fct&gt; &lt;int&gt;
 1 0             0.867 1.33e- 1 0     0           1         0
 2 0             0.943 5.70e- 2 0     0           1         0
 3 0             0.942 5.78e- 2 0     0           1         0
 4 0             0.920 7.96e- 2 0     0           1         0
 5 0             0.903 9.74e- 2 0     0           1         0
 6 0             0.901 9.87e- 2 0     0           1         0
 7 0             1.00  7.89e-12 0     1           1         0
 8 0             1.00  1.24e-12 0     1           1         1
 9 0             0.862 1.38e- 1 0     0           1         0
10 0             0.922 7.76e- 2 0     0           1         0
# ℹ 3,911 more rows
# ℹ 17 more variables: sent_email &lt;fct&gt;, time &lt;dttm&gt;, image &lt;dbl&gt;,
#   attach &lt;dbl&gt;, dollar &lt;dbl&gt;, winner &lt;fct&gt;, inherit &lt;dbl&gt;,
#   viagra &lt;dbl&gt;, password &lt;dbl&gt;, num_char &lt;dbl&gt;, line_breaks &lt;int&gt;,
#   format &lt;fct&gt;, re_subj &lt;fct&gt;, exclaim_subj &lt;dbl&gt;,
#   urgent_subj &lt;fct&gt;, exclaim_mess &lt;dbl&gt;, number &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-5c" class="slide level2 smaller"><h2>Calculating the error rates (5c)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  spam  .pred_class     n
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;
1 0     0            3521
2 0     1              33
3 1     0             299
4 1     1              68</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-5c-1" class="slide level2 smaller"><h2>Calculating the error rates (5c)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a></a>  <span class="fu">group_by</span>(spam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   spam [2]
  spam  .pred_class     n
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;
1 0     0            3521
2 0     1              33
3 1     0             299
4 1     1              68</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-5c-2" class="slide level2 smaller"><h2>Calculating the error rates (5c)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;   &lt;dbl&gt;
1 0     0            3521 0.991  
2 0     1              33 0.00929
3 1     0             299 0.815  
4 1     1              68 0.185  </code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-5c-3" class="slide level2 smaller"><h2>Calculating the error rates (5c)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb25-5"><a></a>         <span class="at">decision =</span> <span class="fu">case_when</span>(</span>
<span id="cb25-6"><a></a>            spam <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">~</span> <span class="st">"True negative"</span>,</span>
<span id="cb25-7"><a></a>            spam <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"False positive"</span>,</span>
<span id="cb25-8"><a></a>            spam <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">~</span> <span class="st">"False negative"</span>,</span>
<span id="cb25-9"><a></a>            spam <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"True positive"</span></span>
<span id="cb25-10"><a></a>        ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   spam [2]
  spam  .pred_class     n       p decision      
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;         
1 0     0            3521 0.991   True negative 
2 0     1              33 0.00929 False positive
3 1     0             299 0.815   False negative
4 1     1              68 0.185   True positive </code></pre>
</div>
</div>
<p>This is where we have AE14 stop….</p>
</section><section id="but-wait" class="slide level2 smaller"><h2>But wait!</h2>
<p>Augment uses a default 50% threshold.</p>
<div class="fragment">
<p>If we change the classification threshold, we change the classifications, and we change the error rates:</p>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb27" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">0.25</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb27-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb27-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n      p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
1 0               0  3263 0.918 
2 0               1   291 0.0819
3 1               0   172 0.469 
4 1               1   195 0.531 </code></pre>
</div>
</div>
</div>
</section><section id="classification-threshold-0.00" class="slide level2 smaller"><h2>Classification threshold: 0.00</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">0.00</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb29-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb29-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
# Groups:   spam [2]
  spam  .pred_class     n     p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1 0               1  3554     1
2 1               1   367     1</code></pre>
</div>
</div>
</section><section id="classification-threshold-0.25" class="slide level2 smaller"><h2>Classification threshold: 0.25</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">0.25</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb31-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb31-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb31-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb31-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n      p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
1 0               0  3263 0.918 
2 0               1   291 0.0819
3 1               0   172 0.469 
4 1               1   195 0.531 </code></pre>
</div>
</div>
</section><section id="classification-threshold-0.5" class="slide level2 smaller"><h2>Classification threshold: 0.5</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">0.50</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb33-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb33-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb33-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1 0               0  3521 0.991  
2 0               1    33 0.00929
3 1               0   299 0.815  
4 1               1    68 0.185  </code></pre>
</div>
</div>
</section><section id="classification-threshold-0.75" class="slide level2 smaller"><h2>Classification threshold: 0.75</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">0.75</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb35-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb35-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1 0               0  3544 0.997  
2 0               1    10 0.00281
3 1               0   339 0.924  
4 1               1    28 0.0763 </code></pre>
</div>
</div>
</section><section id="classification-threshold-1.00" class="slide level2 smaller"><h2>Classification threshold: 1.00</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>spam_aug_all <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&lt;=</span> <span class="fl">1.00</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb37-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb37-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb37-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
# Groups:   spam [2]
  spam  .pred_class     n     p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1 0               0  3554     1
2 1               0   367     1</code></pre>
</div>
</div>
</section><section id="lets-plot-these-error-rates" class="slide level2"><h2>Let’s plot these error rates</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-25-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-curve" class="slide level2 smaller"><h2>ROC curve</h2>
<p>If we repeat this process for “all” possible thresholds <span class="math inline">\(0\leq p^\star\leq 1\)</span>, we trace out the <strong>receiver operating characteristic curve</strong> (ROC curve), which assesses the model’s performance across a range of thresholds:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-26-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-curve-1" class="slide level2 smaller"><h2>ROC curve</h2>
<div class="task">
<p>Which corner of the plot indicates the best model performance?</p>
</div>
<p><img data-src="images/20/roc-curve-annotated.png"> . . .</p>
<p>Upper left!</p>
</section><section id="model-comparison" class="slide level2"><h2>Model comparison</h2>
<p>The farther up and to the left the ROC curve is, the better the classification accuracy. You can quantify this with the area under the curve.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Area under the ROC curve will be our “quality score” for comparing logistic regression models.</p>
</div>
</div>
</div>
</section><section id="roc-for-full-model" class="slide level2 smaller"><h2>ROC for full model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-27-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-for-simple-model" class="slide level2 smaller"><h2>ROC for simple model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="19-logistic-2_files/figure-html/unnamed-chunk-28-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="should-we-include-a-predictor" class="slide level2 smaller"><h2>Should we include a predictor?</h2>
<p>To determine whether we should include a predictor in a model, we should start by asking:</p>
<div>
<ul>
<li class="fragment"><p>Is it ethical to use this variable? (Or even legal?)</p></li>
<li class="fragment"><p>Will this variable be available at prediction time?</p></li>
<li class="fragment"><p>Does this variable contribute to explainability?</p></li>
</ul>
</div>
</section><section><section id="data-splitting-and-spending" class="title-slide slide level1 center"><h1>Data splitting and spending</h1>

</section><section id="weve-been-cheating" class="slide level2 smaller"><h2>We’ve been cheating!</h2>
<div>
<ul>
<li class="fragment"><p>So far, we’ve been using all the data we have for building models. In predictive contexts, this would be considered <em>cheating</em>.</p></li>
<li class="fragment"><p>Evaluating model performance for predicting outcomes that were used when building the models is like evaluating your learning with questions whose answers you’ve already seen.</p></li>
</ul>
</div>
</section><section id="spending-your-data" class="slide level2 smaller"><h2>Spending your data</h2>
<p>For predictive models (used primarily in machine learning), we typically split data into training and test sets:</p>
<p><img data-src="images/20/test-train-split-1.svg" class="quarto-figure quarto-figure-center"> - The <strong>training set</strong> is used for EDA (plots, summary statistics, etc.)</p>
<ul>
<li><p>The <strong>training set</strong> is used to estimate model parameters (fit models).</p></li>
<li><p>The <strong>test set</strong> is used to find an independent assessment of model performance. NEVER look at the test set during training.</p></li>
</ul></section><section id="how-much-to-spend" class="slide level2 smaller"><h2>How much to spend?</h2>
<div>
<ul>
<li class="fragment"><p>The more data we spend (use in training), the better estimates we’ll get.</p></li>
<li class="fragment"><p>Spending too much data in training prevents us from computing a good assessment of predictive performance.</p></li>
<li class="fragment"><p>Spending too much data in testing prevents us from computing a good estimate of model parameters.</p></li>
</ul>
</div>
</section><section id="the-initial-split" class="slide level2 smaller"><h2>The initial split</h2>
<p>Randomly pick training and testing rows!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">set.seed</span>(<span class="dv">20241112</span>)</span>
<span id="cb39-2"><a></a>email_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(email)</span>
<span id="cb39-3"><a></a>email_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;2940/981/3921&gt;</code></pre>
</div>
</div>
<div class="fragment">
<p>Default: 75% training; 25% testing</p>
</div>
</section><section id="the-initial-split-1" class="slide level2 smaller"><h2>The initial split</h2>
<p>Change proportion:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">set.seed</span>(<span class="dv">20250612</span>)</span>
<span id="cb41-2"><a></a>email_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(email, <span class="at">prop =</span> <span class="fl">0.8</span>)</span>
<span id="cb41-3"><a></a>email_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;3136/785/3921&gt;</code></pre>
</div>
</div>
</section><section id="setting-a-seed" class="slide level2 smaller"><h2>Setting a seed</h2>
<div class="task">
<p>What does <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> do?</p>
</div>
<div>
<ul>
<li class="fragment"><p>To create that split of the data, R generates “pseudo-random” numbers: while they are made to behave like random numbers, their generation is deterministic given a “seed”.</p></li>
<li class="fragment"><p>This allows us to reproduce results by setting that seed.</p></li>
<li class="fragment"><p>Which seed you pick doesn’t matter, as long as you don’t try a bunch of seeds and pick the one that gives you the best performance.</p></li>
</ul>
</div>
</section><section id="accessing-the-data" class="slide level2 smaller"><h2>Accessing the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>email_train <span class="ot">&lt;-</span> <span class="fu">training</span>(email_split)</span>
<span id="cb43-2"><a></a>email_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(email_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="the-training-set" class="slide level2 smaller"><h2>The training set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a>email_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,136 × 21
   spam  to_multiple from     cc sent_email time                image
   &lt;fct&gt; &lt;fct&gt;       &lt;fct&gt; &lt;int&gt; &lt;fct&gt;      &lt;dttm&gt;              &lt;dbl&gt;
 1 0     0           1         0 0          2012-02-18 14:20:54     0
 2 1     0           1         0 0          2012-03-10 17:43:58     0
 3 0     1           1         0 0          2012-03-06 09:10:00     0
 4 1     0           1         0 0          2012-03-18 09:26:41     0
 5 0     0           1         0 1          2012-03-15 20:47:33     0
 6 0     0           1         0 1          2012-03-31 09:24:03     0
 7 0     0           1         0 0          2012-02-16 11:25:22     0
 8 0     0           1         0 0          2012-02-24 18:18:35     0
 9 0     1           1         0 1          2012-01-22 04:02:27     0
10 0     0           1         0 0          2012-02-10 19:46:30     0
# ℹ 3,126 more rows
# ℹ 14 more variables: attach &lt;dbl&gt;, dollar &lt;dbl&gt;, winner &lt;fct&gt;,
#   inherit &lt;dbl&gt;, viagra &lt;dbl&gt;, password &lt;dbl&gt;, num_char &lt;dbl&gt;,
#   line_breaks &lt;int&gt;, format &lt;fct&gt;, re_subj &lt;fct&gt;,
#   exclaim_subj &lt;dbl&gt;, urgent_subj &lt;fct&gt;, exclaim_mess &lt;dbl&gt;,
#   number &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="the-testing-data" class="slide level2 smaller"><h2>The testing data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a>email_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 785 × 21
   spam  to_multiple from     cc sent_email time                image
   &lt;fct&gt; &lt;fct&gt;       &lt;fct&gt; &lt;int&gt; &lt;fct&gt;      &lt;dttm&gt;              &lt;dbl&gt;
 1 0     1           1         1 1          2012-01-01 13:45:21     1
 2 0     0           1         0 1          2012-01-01 13:23:44     0
 3 0     0           1         1 1          2012-01-01 18:40:14     0
 4 0     0           1         0 0          2012-01-01 21:51:24     0
 5 0     0           1         2 0          2012-01-01 23:07:57     0
 6 0     0           1         0 0          2012-01-02 09:35:56     0
 7 0     0           1         0 0          2012-01-02 10:12:51     0
 8 0     0           1         5 0          2012-01-02 12:48:26     0
 9 0     1           1         1 0          2012-01-02 10:27:07     0
10 0     0           1         7 0          2012-01-02 19:07:51     0
# ℹ 775 more rows
# ℹ 14 more variables: attach &lt;dbl&gt;, dollar &lt;dbl&gt;, winner &lt;fct&gt;,
#   inherit &lt;dbl&gt;, viagra &lt;dbl&gt;, password &lt;dbl&gt;, num_char &lt;dbl&gt;,
#   line_breaks &lt;int&gt;, format &lt;fct&gt;, re_subj &lt;fct&gt;,
#   exclaim_subj &lt;dbl&gt;, urgent_subj &lt;fct&gt;, exclaim_mess &lt;dbl&gt;,
#   number &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="ae-15" class="slide level2"><h2>AE 15</h2>
<ul>
<li>Create a train and test split</li>
<li>Fit models</li>
<li>Test and evaluate models</li>
</ul></section></section><section><section id="washington-forests" class="title-slide slide level1 center"><h1>Washington forests</h1>

</section><section id="data-1" class="slide level2 smaller"><h2>Data</h2>
<ul>
<li><p>The U.S. Forest Service maintains machine learning models to predict whether a plot of land is “forested.”</p></li>
<li><p>This classification is important for research, legislation, land management, etc. purposes.</p></li>
<li><p>Plots are typically remeasured every 10 years.</p></li>
<li><p>The <code>forested</code> dataset contains the most recent measurement per plot.</p></li>
</ul></section><section id="data-forested" class="slide level2 smaller"><h2>Data: <code>forested</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a>forested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,107 × 19
   forested  year elevation eastness northness roughness tree_no_tree
   &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;       
 1 Yes       2005       881       90        43        63 Tree        
 2 Yes       2005       113      -25        96        30 Tree        
 3 No        2005       164      -84        53        13 Tree        
 4 Yes       2005       299       93        34         6 No tree     
 5 Yes       2005       806       47       -88        35 Tree        
 6 Yes       2005       736      -27       -96        53 Tree        
 7 Yes       2005       636      -48        87         3 No tree     
 8 Yes       2005       224      -65       -75         9 Tree        
 9 Yes       2005        52      -62        78        42 Tree        
10 Yes       2005      2240      -67       -74        99 No tree     
# ℹ 7,097 more rows
# ℹ 12 more variables: dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;,
#   temp_annual_mean &lt;dbl&gt;, temp_annual_min &lt;dbl&gt;,
#   temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;, vapor_min &lt;dbl&gt;,
#   vapor_max &lt;dbl&gt;, canopy_cover &lt;dbl&gt;, lon &lt;dbl&gt;, lat &lt;dbl&gt;,
#   land_type &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="data-forested-1" class="slide level2 smaller"><h2>Data: <code>forested</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a><span class="fu">glimpse</span>(forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,107
Columns: 19
$ forested         &lt;fct&gt; Yes, Yes, No, Yes, Yes, Yes, Yes, Yes, Yes,…
$ year             &lt;dbl&gt; 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2…
$ elevation        &lt;dbl&gt; 881, 113, 164, 299, 806, 736, 636, 224, 52,…
$ eastness         &lt;dbl&gt; 90, -25, -84, 93, 47, -27, -48, -65, -62, -…
$ northness        &lt;dbl&gt; 43, 96, 53, 34, -88, -96, 87, -75, 78, -74,…
$ roughness        &lt;dbl&gt; 63, 30, 13, 6, 35, 53, 3, 9, 42, 99, 51, 19…
$ tree_no_tree     &lt;fct&gt; Tree, Tree, Tree, No tree, Tree, Tree, No t…
$ dew_temp         &lt;dbl&gt; 0.04, 6.40, 6.06, 4.43, 1.06, 1.35, 1.42, 6…
$ precip_annual    &lt;dbl&gt; 466, 1710, 1297, 2545, 609, 539, 702, 1195,…
$ temp_annual_mean &lt;dbl&gt; 6.42, 10.64, 10.07, 9.86, 7.72, 7.89, 7.61,…
$ temp_annual_min  &lt;dbl&gt; -8.32, 1.40, 0.19, -1.20, -5.98, -6.00, -5.…
$ temp_annual_max  &lt;dbl&gt; 12.91, 15.84, 14.42, 15.78, 13.84, 14.66, 1…
$ temp_january_min &lt;dbl&gt; -0.08, 5.44, 5.72, 3.95, 1.60, 1.12, 0.99, …
$ vapor_min        &lt;dbl&gt; 78, 34, 49, 67, 114, 67, 67, 31, 60, 79, 17…
$ vapor_max        &lt;dbl&gt; 1194, 938, 754, 1164, 1254, 1331, 1275, 944…
$ canopy_cover     &lt;dbl&gt; 50, 79, 47, 42, 59, 36, 14, 27, 82, 12, 74,…
$ lon              &lt;dbl&gt; -118.6865, -123.0825, -122.3468, -121.9144,…
$ lat              &lt;dbl&gt; 48.69537, 47.07991, 48.77132, 45.80776, 48.…
$ land_type        &lt;fct&gt; Tree, Tree, Tree, Tree, Tree, Tree, Non-tre…</code></pre>
</div>
</div>
</section><section id="outcome-and-predictors" class="slide level2 smaller"><h2>Outcome and predictors</h2>
<ul>
<li>Outcome: <code>forested</code> - Factor, <code>Yes</code> or <code>No</code>
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="fu">levels</span>(forested<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
<ul>
<li>
<p>Predictors: 18 remotely-sensed and easily-accessible predictors:</p>
<ul>
<li><p>numeric variables based on weather and topography</p></li>
<li><p>categorical variables based on classifications from other governmental organizations</p></li>
</ul>
</li>
</ul></section><section id="forested" class="slide level2"><h2><code>?forested</code></h2>
<iframe width="900" height="500" src="https://simonpcouch.github.io/forested/reference/forested.html" title="forested" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


</section></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://sta199-su25.github.io/">🔗 sta199-su25.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="../site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="../site_libs/revealjs/plugin/notes/notes.js"></script><script src="../site_libs/revealjs/plugin/search/search.js"></script><script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="../site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': true,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/sta199-su25\.github\.io\/");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>


</body></html>