{
  "hash": "26622ba45505ffdb26ce8d1f3c3d1942",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nsubtitle: \"Lecture 15\"\ndate: \"2025-06-05\"\nformat: \n  revealjs:\n    output-file: 15-mult-reg-slides.html\n---\n\n\n\n\n\n## Announcements\n\n-   Office hours today: 1-3pm; old chem 203\n\n-   Math warning: logarithms\n\n-   Let me know if your Milestone 2 is ready to grade!\n\n## Simple Linear Regression\n\n-   A single quantitative $x$ and $y$\n\n-   Population Model:\n\n    $$\n    Y = \\beta_0 + \\beta_1 X + \\epsilon\n    $$\n\n-   Regression Line:\n\n    $$\n    \\hat{Y} = b_0 + b_1 X\n    $$\n\n# Regression with Categorical Variables\n\n## Regression with Categorical Variables {.smaller}\n\n*It's possible to want to model an outcome based on a categorical predictor:*\n\n$$ Y = \\beta_0 + \\beta_1 X + \\epsilon$$\n\nWhat does this even mean when $x$ is categorical ???\n\n# Movie Example\n\n## Example Data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 146 × 3\n   critics audience imdb_cat\n     <int>    <int> <chr>   \n 1      74       86 High    \n 2      85       80 Med     \n 3      80       90 High    \n 4      18       84 Low     \n 5      14       28 Low     \n 6      63       62 Med     \n 7      42       53 Med     \n 8      86       64 Med     \n 9      99       82 High    \n10      89       87 High    \n# ℹ 136 more rows\n```\n\n\n:::\n:::\n\n\n## Example Data: Visualization {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-mult-reg_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Let's just try it... {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovies_fit <- linear_reg() |>\n  fit(audience ~ imdb_cat, data = movie_scores)\n\ntidy(movies_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     85.1      1.73     49.1  2.29e-91\n2 imdb_catLow    -45.8      2.57    -17.8  3.89e-38\n3 imdb_catMed    -21.6      2.20     -9.83 9.83e-18\n```\n\n\n:::\n:::\n\n\nWhat's going on??\n\n## What's going on? {.smaller}\n\nVariable `imdb_cat` can take values *high, med,* or *low.* We want to model variable `audience` based on `imdb_cat`.\n\n. . .\n\nWe tell R to fit `audience ~ imdb_cat` ... now what?\n\n. . .\n\n[We get ***dummy variables!!!***]{style=\"background-color: #fcefb3\"}\n\n## Dummy Variables {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n| audience | imdb_cat |\n|----------|----------|\n| 70       | high     |\n| 40       | low      |\n| 50       | med      |\n| 80       | high     |\n:::\n:::\n\n## Dummy Variables {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n| audience | imdb_cat |\n|----------|----------|\n| 70       | high     |\n| 40       | low      |\n| 50       | med      |\n| 80       | high     |\n:::\n\n::: {.column width=\"50%\"}\n| audience | imdb_cat | high | low | med |\n|----------|----------|------|-----|-----|\n| 70       | high     |      |     |     |\n| 40       | low      |      |     |     |\n| 50       | med      |      |     |     |\n| 80       | high     |      |     |     |\n:::\n:::\n\n. . .\n\n::: callout-important\nIn a given row, only *one* of the dummy variables for a given categorical variable can equal 1.\n:::\n\n## Write the regression output: {.smaller}\n\nUsing the categorical variable?\n\n$$\n\\widehat{audience} = b_0 + b_1 \\times imdb\\_cat\n$$\n\n<br><br><br>\n\n❌ WRONG ❌ 🛑 DON'T DO THIS 🛑 ❗SERIOUSLY ❗💔 Don't make me sad :( 💔\n\n## What will a regression output look like? {.smaller}\n\nUse the dummy variables!!\n\n$$\n\\widehat{audience} = b_0 + b_1 \\times low + b_2  \\times med\n$$\n\n## What will a regression output look like? {.smaller}\n\nUse the dummy variables!!\n\n$$\n\\widehat{audience} = b_0 + b_1 \\times low + b_2 \\times med\n$$\n\n<br><br><br>\n\n::: callout-important\nAll levels except the **baseline level** will show up in the output.\nHere, high is the **baseline level.** You will be able to identify the baseline by looking at the data and the output!\n:::\n\n## Interpret the output: {.smaller}\n\n$$\n\\widehat{audience} = b_0 + b_1 \\times low + b_2 \\times med\n$$\n\n-   (Intercept) $b_0$ ?\n\n<br>\n\n-   (Slope) $b_1$ ?\n\n<br>\n\n-   (Slope) $b_2$ ?\n\n## Let's plug in some numbers: {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovies_fit <- linear_reg() |>\n  fit(audience ~ imdb_cat, data = movie_scores)\n\ntidy(movies_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     85.1      1.73     49.1  2.29e-91\n2 imdb_catLow    -45.8      2.57    -17.8  3.89e-38\n3 imdb_catMed    -21.6      2.20     -9.83 9.83e-18\n```\n\n\n:::\n:::\n\n\n<br>\n\n$$\n\\widehat{audience} = 85.1 -45.8 \\times low -21.6 \\times med\n$$\n\n## Interpretation with numbers: {.smaller}\n\n$$\n\\widehat{audience} = 85.1 -45.8 \\times low -21.6 \\times med\n$$\n\n<br>\n\n-   Expected audience score of high IMDB rating movies: 85.1\n\n-   Movies with low IMDB ratings are expected to have, on average, audience scores 45.8 points lower than movies with high IMDB ratings\n\n-   Movies with medium IMDB ratings are expected to have, on average, audience scores 21.6 points lower than movies with high IMDB ratings\n\n# In General\n\n## Generally: {.smaller}\n\nPredicting [continuous outcome]{style=\"background-color: #fcefb3\"} $y$ using [categorical explanatory variable]{style=\"background-color: #fcefb3\"} $x$ with levels $cat_0, \\ldots cat_L$:\n\n## Generally: {.smaller}\n\nPredicting [continuous outcome]{style=\"background-color: #fcefb3\"} $y$ using [categorical explanatory variable]{style=\"background-color: #fcefb3\"} $x$ with levels $cat_0, \\ldots cat_L$:\n\n$$\n\\hat{y} = b_0 + b_1 \\times cat_1 + b_2 \\times cat_2 \\ldots + b_L \\times cat_L\n$$\n\n## Generally: {.smaller}\n\nPredicting [continuous outcome]{style=\"background-color: #fcefb3\"} $y$ using [categorical explanatory variable]{style=\"background-color: #fcefb3\"} $x$ with levels $cat_0, \\ldots cat_L$:\n\n$$\n\\hat{y} = b_0 + b_1 \\times cat_1 + b_2 \\times cat_2 \\ldots + b_L \\times cat_L\n$$\n\n-   $b_0$ : On average, expected $y$ for an entry of **baseline level** $cat_0$\n\n<br>\n\n-   $b_1$: On average, we expect the $y$ for an observation of level $cat_1$ to be be $b_1$ larger (smaller if negative) than a baseline $cat_0$ observation <br>\n\n<br>\n\n-   and so on....\n\n##  {.smaller}\n\n## Back to AE-12! {.smaller}\n",
    "supporting": [
      "15-mult-reg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}