{
  "hash": "d0b127fa47d48ede11a1028ee70e52ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nsubtitle: \"Lecture 15\"\ndate: \"2025-06-05\"\nformat: \n  revealjs:\n    output-file: 15-mult-reg-slides.html\n    pdf-separate-fragments: true\n---\n\n\n\n\n\n## Announcements\n\n-   Do your team peer evaluations!\n\n-   Milestone 2 will be graded by tomorrow morning! Pick your data sets ASAP.\n\n-   Tomorrow we will talk about some project details at the beginning of class - please try to be here!!\n\n## Midterms are Graded... {.smaller}\n\n-   Scores will be posted later today. \n\n-   In class: score out of 70\n\n-   Take home: score out of 30\n\n-   Overall midterm grade: add the two scores together!\n\n## Tomorrow {.smaller}\n\n-   Scores will be posted later today. \n\n-   In class: score out of 70\n\n-   Take home: score out of 30\n\n-   Overall midterm grade: add the two scores together!\n\n# Quick Review\n\n## Simple Linear Regression {.smaller}\n\n-   A single quantitative $x$ and $y$\n\n-   Population Model:\n\n    $$\n    Y = \\beta_0 + \\beta_1 X + \\epsilon\n    $$\n\n-   Regression Line:\n\n    $$\n    \\hat{Y} = b_0 + b_1 X\n    $$\n\n## Linear Regression with one Categorical Predictor {.smaller}\n\n-   A single categorical $x$ and quantitative $y$\n\n-   R creates *dummy variables* for each level of the categorical predictor\n\n-   The result has one intercept (predicted $y$ for baseline level) and one slope for each non-baseline level\n\n## Linear Regression with one Categorical Predictor: Example {.smaller}\n\nWe are predicting audience scores using variable `imdb_cat` with levels `low`, `medium`, and `high`:\n\n$$\n\\widehat{audience} = 85.1 -45.8 \\times low -21.6 \\times med\n$$\n\n. . .\n\n-   Expected audience score of high IMDB rating movies: 85.1\n\n. . .\n\n-   Movies with low IMDB ratings are expected to have, on average, audience scores 45.8 points lower than movies with high IMDB ratings\n\n. . .\n\n-   Movies with medium IMDB ratings are expected to have, on average, audience scores 21.6 points lower than movies with high IMDB ratings\n\n# Multiple Predictors\n\n## Additive vs. Interaction {.smaller}\n\nBoth of these use `flipper_length_mm` *and* `island` to predict `body_mass_g`:\n\n\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](16-mult-reg-2_files/figure-html/additive-interaction-viz-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](16-mult-reg-2_files/figure-html/additive-interaction-viz-2.png){width=672}\n:::\n:::\n\n\n## The additive model: parallel lines, one for each island {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm + island, data = penguins)\n\ntidy(bm_fl_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        -4625.     392.      -11.8  4.29e-27\n2 flipper_length_mm     44.5      1.87     23.9  1.65e-74\n3 islandDream         -262.      55.0      -4.77 2.75e- 6\n4 islandTorgersen     -185.      70.3      -2.63 8.84e- 3\n```\n\n\n:::\n:::\n\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n## Where do the three lines come from? {.smaller}\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n## How do we interpret this in English? {.smaller}\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n-   Intercept: We expect, [on average]{.underline}, penguins from **Biscoe** island with **0mm flipper length** to weigh **-4625 grams**\n\n## How do we interpret this in English? {.smaller}\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n-   Slope (flipper length) : ***Holding island constant,*** we expect, on average, a **1mm** increase in flipper length corresponds to a **44.5g** increase in body mass\n\n## How do we interpret this in English? {.smaller}\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n-   Slope (dream) : ***Holding flipper length constant,*** we expect, [on average]{.underline}, a penguin from the **Dream island** to be **262g lighter** than a penguin from **Biscoe** island.\n\n# The Interaction Model\n\n## The interaction model: different slopes for each island {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_int_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm * island, data = penguins)\n\ntidy(bm_fl_island_int_fit) |> select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  term                              estimate\n  <chr>                                <dbl>\n1 (Intercept)                        -5464. \n2 flipper_length_mm                     48.5\n3 islandDream                         3551. \n4 islandTorgersen                     3218. \n5 flipper_length_mm:islandDream        -19.4\n6 flipper_length_mm:islandTorgersen    -17.4\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -5464 + 48.5 \\times flipper~length &+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$\n\n## Where do the three lines come from? {.smaller}\n\n$$\n\\begin{aligned}\n\\small\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length \\\\\n&+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$\n\nIf penguin is from Biscoe, Dream = 0 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length\n\\end{aligned}\n$$\n\n## Where do the three lines come from? {.smaller}\n\n$$\n\\begin{aligned}\n\\small\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length \\\\\n&+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$\n\nIf penguin is from Dream, Dream = 1 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} &= (-5464 + 3551) + (48.5-19.4) \\times flipper~length\\\\\n&=-1913+29.1\\times flipper~length.\n\\end{aligned}\n$$\n\n## You try! {.smaller}\n\n$$\n\\begin{aligned}\n\\small\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length \\\\\n&+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$ If penguin is from Torgersen, Dream = 0 and Torgersen = 1:\n\n## Interpretation {.smaller}\n\nWe can interpret each of the lines just as we would a simple linear regression, keeping in mind that we are only looking at penguins from one specific island.\n\n. . .\n\n**Dream Penguins:** $\\widehat{body~mass} = -1913 + 29.1 \\times flipper~length$\n\n. . .\n\n-   **Intercept:** For penguins from Dream island, a flipper length of 0 corresponds to, on average, a body mass of -1913 grams.\n\n. . .\n\n-   **Slope:** For penguins from Dream island, a 1mm increase in flipper length corresponds to, on average, a body mass increase of 29.1 grams.\n\n## Prediction {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm = 200,\n  island = \"Torgersen\"\n)\n\npredict(bm_fl_island_int_fit, new_data = new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 3980.\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{body~mass} = (-5464 + 3218) + (48.5-17.4) \\times 200.\n$$\n\n## Multiple Numerical Predictors {.smaller}\n\nWhat if we want to use multiple numerical predictors to model a numerical outcome?\n\nExample:\n\n-   Using flipper length and bill length to predict body mass.\n\n-   Using Rotten Tomato critic score + metacritic score to predict audience score\n\n-   So many more!!\n\n## Multiple Numerical Predictors: Example {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_bl_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm * bill_length_mm, data = penguins)\n\ntidy(bm_fl_bl_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                            estimate std.error statistic p.value\n  <chr>                              <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)                      5091.    2925.        1.74  8.27e-2\n2 flipper_length_mm                  -7.31    15.0      -0.486 6.27e-1\n3 bill_length_mm                   -229.      63.4      -3.61  3.47e-4\n4 flipper_length_mm:bill_length_…     1.20     0.322     3.72  2.32e-4\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\n\\small\\widehat{body~mass}=-5736+48.1\\times flipper~length+6\\times bill~length\n$$\n\n## Multiple Numerical Predictors: Interpretation {.smaller}\n\n$$\n\\small\\widehat{body~mass}=-5736+48.1\\times flipper~length+6\\times bill~length\n$$\n\n::: incremental\n- We predict that the body mass of a penguin with *zero* flipper length and *zero* bill length will be -5736 grams, on average (**makes no sense**);\n- Holding all other variables constant, for every additional millimeter in flipper length, we expect the body mass of penguins to be higher, on average, by 48.1 grams.\n- Holding all other variables constant, for every additional millimeter in bill length, we expect the body mass of penguins to be higher, on average, by 6 grams.\n:::\n\n. . . \n\nThis is how we interpret additive models with as many predictors as we want!\n\n## Prediction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm = 200,\n  bill_length_mm = 45\n)\n\npredict(bm_fl_bl_fit, new_data = new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4112.\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{body~mass}=-5736+48.1\\times 200+6\\times 45\n$$\n\n## Picture? It's not pretty...\n\n2 predictors + 1 response = 3 dimensions. Ick!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-mult-reg-2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Picture? It's not pretty...\n\nInstead of a line of best fit, it's a *plane* of best fit. Double ick!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-mult-reg-2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Multiple Numerical Predictors: With Interaction {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_bl_int_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm * bill_length_mm, data = penguins)\n\ntidy(bm_fl_bl_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                            estimate std.error statistic p.value\n  <chr>                              <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)                      5091.    2925.        1.74  8.27e-2\n2 flipper_length_mm                  -7.31    15.0      -0.486 6.27e-1\n3 bill_length_mm                   -229.      63.4      -3.61  3.47e-4\n4 flipper_length_mm:bill_length_…     1.20     0.322     3.72  2.32e-4\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\n\\begin{aligned}\n\\small \\widehat{body~mass} =\\;& 5090.5 - 7.3 \\times flipper \\\\\n&- 229.2 \\times bill \\\\\n&+ 1.2 \\times flipper \\times bill\n\\end{aligned}\n$$\n\n\n## What does this model mean? {.smaller}\n\n- We still have an intercept and main effects for both `flipper` and `bill`. **But now we also have an interaction term.** \n\n. . .\n\n- This means: the **effect of flipper length depends on bill length**, and vice versa. \n\n. . .\n\n- In additive models: each variable has a fixed slope.\n- In interaction models: **the slope of one predictor varies depending on the level of the other.** \n\n# AE 13: Modelling House Prices ",
    "supporting": [
      "16-mult-reg-2_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}