---
title: "AE 08: Data Types"
subtitle: "Suggested answers"
format:
  html:
    self-contained: true
---

## Packages

We will use the tidyverse package in this application exercise.

```{r}
library(tidyverse)
```

## Data

The data come from https://www.usclimatedata.com/climate/durham/north-carolina/united-states/usnc0192 and are stored as `durham-climate.csv` in the `data` folder.

```{r}
durham_climate <- read_csv("data/durham-climate.csv")
```

```{r}
durham_climate
```

**Question:** What data types are each of these columns?

## Factor Reordering

Let's talk about the following plot:

```{r}
ggplot(
  durham_climate, 
  aes(x = month, y = avg_high_f, group = 1)
  ) +
  geom_line() +
  geom_point(
    shape = "circle filled", size = 2,
    color = "black", fill = "white", stroke = 1
  ) +
  labs(
    x = "Month",
    y = "Average high temperature (F)",
    title = "Durham climate"
  )
```

What is wrong here?

Let's fix the plot by re-ordering our factors:

```{r}

durham_climate <- durham_climate |>
  mutate(month = fct_relevel(month, c("January", "February", "March",
                                      "April", "May", "June", "July", "August", 
                                      "September", "October", "November", "December")))


ggplot(
  durham_climate, 
  aes(x = month, y = avg_high_f, group = 1)
  ) +
  geom_line() +
  geom_point(
    shape = "circle filled", size = 2,
    color = "black", fill = "white", stroke = 1
  ) +
  labs(
    x = "Month",
    y = "Average high temperature (F)",
    title = "Durham climate"
  )

```
