---
title: "AE 10: More Practice"
format:
  html:
    self-contained: true
---

# Durham Climate Data

We will use the `tidyverse` library today.

```{r}
library(tidyverse)
```

As a refresher, is the code from AE-08:

**Read in data:**

```{r}
durham_climate <- read_csv("data/durham-climate.csv")
```

**Relevel factors:**

```{r}
durham_climate <- durham_climate |>
  mutate(month = fct_relevel(month, c("January", "February", "March",
                                      "April", "May", "June", "July", "August", 
                                      "September", "October", "November", "December")))
```

**Plot:**

```{r}
ggplot(
  durham_climate, 
  aes(x = month, y = avg_high_f, group = 1)
  ) +
  geom_line() +
  geom_point(
    shape = "circle filled", size = 2,
    color = "black", fill = "white", stroke = 1
  ) +
  labs(
    x = "Month",
    y = "Average high temperature (F)",
    title = "Durham climate"
  )
```

## Goal : Beautify the plot

```{r}
durham_climate <- durham_climate |>
  mutate(month = fct_relevel(month, c("January", "February", "March",
                                      "April", "May", "June", "July",
                                      "August", "September", "October",
                                      "November", "December")))
durham_climate <- durham_climate |>
  mutate( season = case_when(
      month %in% c("December", "January", "February") ~ "Winter",
      month %in% c("March", "April", "May") ~ "Spring",
      month %in% c("June", "July", "August") ~ "Summer",
      month %in% c("September", "October", "November") ~ "Fall",)
    ) |>
  mutate(season = fct_relevel(season, "Winter", "Spring", "Summer", "Fall"))
durham_climate |> ggplot(aes(x = month, y = avg_high_f,
                             group = 1, fill = season)) +
  geom_line() +
  geom_point(shape = "circle filled", size = 3, stroke = 1) +
  scale_fill_manual(
    values = c(
        "Winter" = "lightskyblue1",
        "Spring" = "chartreuse3",
        "Summer" = "gold2",
        "Fall" = "lightsalmon4")) +
  labs(
      x = "Month",
      y = "Average high temperature (F)",
      title = "Durham climate",
      fill = "Season") +
  theme_minimal() +
  theme(legend.position = "top")
```

## Goal : Pivot + Multiple Lines!

**Add your pivot code here:**

```{r}

```

**Check out the plot!**

```{r}
#| eval: false

durham_climate |>
  ggplot(aes(x = month, y = temp, group = temp_type, color = temp_type, fill = season)) +
    geom_line() +
    geom_point(shape = "circle filled", size = 3, stroke = 1) +
    scale_fill_manual(
      values = c(
        "Winter" = "lightskyblue1",
        "Spring" = "chartreuse3",
        "Summer" = "gold2",
        "Fall" = "lightsalmon4"
      )
    ) +
    scale_color_manual(
      values = c(
        "avg_high_f" = "gray20",
        "avg_low_f" = "gray70"
      )
    ) +
    labs(
      x = "Month",
      y = "Average temperature (F)",
      title = "Durham climate",
      fill = "Season",
      color = "Type"
    ) +
    theme_minimal() +
    theme(legend.position = "top")
```
